name: Create Release on Commit

on:
  push:
    branches:
      - main
    paths:
      - '**/*.pak/**'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Create a ZIP file of the repository excluding certain files
      - name: Create ZIP Package
        run: zip -r minui-favorites.zip ./* -x ".github" "LICENSE" "README.md"

      # Create a Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: "1.${{ github.run_number }}"
          release_name: "Release 1.${{ github.run_number }}"
          body: "Automated release for commit ${{ github.sha }}"
          draft: false
          prerelease: false

      # Upload the ZIP file to the release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: minui-favorites.zip
          asset_name: minui-favorites.zip
          asset_content_type: application/zip